//! 构建时图片转换:assets 目录 → images.rs(RGB565 位图数组)。
//! 用法(固件 crate 的 build.rs):
//! `qingui_codegen::convert("assets", &std::env::var("OUT_DIR").unwrap());`
//! 然后 `include!(concat!(env!("OUT_DIR"), "/images.rs"));`

use image::AnimationDecoder as _;
use std::fmt::Write as _;
use std::path::Path;

/// 扫描 assets_dir,把 png/jpg/jpeg 转为单帧、gif 转为多帧 ImageData,
/// 在 out_dir 生成 images.rs。透明通道直接丢弃;gif 每帧按完整帧处理。
pub fn convert(assets_dir: &str, out_dir: &str) -> std::io::Result<()> {
    let mut code = String::from("// @generated by qingui-codegen; DO NOT EDIT\n");
    let mut entries: Vec<_> = std::fs::read_dir(assets_dir)?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_file())
        .collect();
    entries.sort();
    for path in entries {
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("").to_ascii_lowercase();
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
        let name = to_screaming_snake(stem);
        let frames: Vec<(i32, i32, Vec<u8>, u16)> = match ext.as_str() {
            "png" | "jpg" | "jpeg" => {
                let img = image::open(&path).map_err(to_ioe)?.to_rgba8();
                let (w, h) = (img.width() as i32, img.height() as i32);
                vec![(w, h, rgba_to_565(img.as_raw()), 0)]
            }
            "gif" => decode_gif(&path)?,
            _ => continue,
        };
        write_static(&mut code, &name, &frames);
    }
    std::fs::write(Path::new(out_dir).join("images.rs"), code)
}

fn decode_gif(path: &Path) -> std::io::Result<Vec<(i32, i32, Vec<u8>, u16)>> {
    let file = std::io::BufReader::new(std::fs::File::open(path)?);
    let dec = image::codecs::gif::GifDecoder::new(file).map_err(to_ioe)?;
    let mut out = Vec::new();
    for f in dec.into_frames().collect::<Result<Vec<_>, _>>().map_err(to_ioe)? {
        let (numer, denom) = f.delay().numer_denom_ms();
        let ms = (numer / denom.max(1)).max(1) as u16;
        let buf = f.into_buffer();
        out.push((buf.width() as i32, buf.height() as i32, rgba_to_565(buf.as_raw()), ms));
    }
    Ok(out)
}

fn rgba_to_565(rgba: &[u8]) -> Vec<u8> {
    let mut v = Vec::with_capacity(rgba.len() / 2);
    for px in rgba.chunks_exact(4) {
        // 5-6-5 truncation (encode-side quantization; qingui's `blit565` decode expands losslessly).
        let c = (((px[0] as u16) & 0xF8) << 8) | (((px[1] as u16) & 0xFC) << 3) | ((px[2] as u16) >> 3);
        v.push((c & 0xFF) as u8);
        v.push((c >> 8) as u8);
    }
    v
}

fn write_static(code: &mut String, name: &str, frames: &[(i32, i32, Vec<u8>, u16)]) {
    let _ = writeln!(code, "pub static {name}: qingui::widgets::image::ImageData = qingui::widgets::image::ImageData {{");
    let _ = writeln!(code, "    frames: &[");
    for (w, h, data, _ms) in frames {
        let _ = write!(code, "        qingui::widgets::image::Frame {{ w: {w}, h: {h}, rgb565: &[");
        for (i, b) in data.iter().enumerate() {
            if i > 0 { let _ = write!(code, ", "); }
            let _ = write!(code, "0x{b:02X}");
        }
        let _ = writeln!(code, "] }},");
    }
    let _ = writeln!(code, "    ],");
    let delays: Vec<String> = frames.iter().map(|f| f.3.to_string()).collect();
    let _ = writeln!(code, "    delays_ms: &[{}],", delays.join(", "));
    let _ = writeln!(code, "}};");
}

fn to_screaming_snake(stem: &str) -> String {
    let mut out = String::new();
    for (i, ch) in stem.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    out
}

fn to_ioe(e: image::ImageError) -> std::io::Error {
    std::io::Error::new(std::io::ErrorKind::InvalidData, e)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Locks the encode-side 5-6-5 truncation formula's own values; the formula
    // no longer duplicates anything on the qingui side.
    #[test]
    fn rgba_to_565_locks_truncation_formula() {
        assert_eq!(rgba_to_565(&[255, 255, 255, 255]), [0xFF, 0xFF]); // white -> 0xFFFF
        assert_eq!(rgba_to_565(&[255, 0, 0, 255]), [0x00, 0xF8]); // pure red -> 0xF800
        // Mid-range case locking the 6-bit green mask and little-endian byte order.
        assert_eq!(rgba_to_565(&[0, 255, 0, 255]), [0xE0, 0x07]); // pure green -> 0x07E0
    }
}
