use crate::arena::ObjRef;
use crate::geometry::Rect;
use crate::pixel::PixelFormat;
use crate::style::Style;
use crate::ui::Ui;
use super::builder::{CommonBuilder, WidgetBuilder, WidgetCfg};
use super::{TickOut, WidgetCtx};

/// One frame of an RGB565 (little-endian) bitmap
pub struct Frame {
    pub w: i32,
    pub h: i32,
    pub rgb565: &'static [u8],
}

/// Image data: a single frame for static images; multiple frames + per-frame delay for gifs. Generated by qingui-codegen
pub struct ImageData {
    pub frames: &'static [Frame],
    pub delays_ms: &'static [u16],
}

/// Image widget state: current frame index and the last switch time.
pub struct ImageState {
    pub data: &'static ImageData,
    pub cur: usize,
    pub last_switch: u64,
}

impl<C: PixelFormat> super::Widget<C> for ImageState {
    fn draw(&self, ctx: &WidgetCtx, c: &mut super::Canvas<'_, C>, clip: Rect) {
        let Some(f) = self.data.frames.get(self.cur) else { return };
        c.blit565(ctx.abs.x, ctx.abs.y, f.w, f.h, f.rgb565, clip);
    }
    fn tick(&mut self, _ui: &mut Ui<C>, _obj: ObjRef, now: u64) -> TickOut {
        if self.data.frames.len() <= 1 {
            return TickOut::IDLE;
        }
        let delay = self.data.delays_ms.get(self.cur).copied().unwrap_or(100) as u64;
        if now.saturating_sub(self.last_switch) >= delay {
            self.cur = (self.cur + 1) % self.data.frames.len();
            self.last_switch = now;
            TickOut { redraw: true, active: true }
        } else {
            TickOut { redraw: false, active: true }
        }
    }
    fn as_any(&self) -> &dyn core::any::Any { self }
    fn as_any_mut(&mut self) -> &mut dyn core::any::Any { self }
}

/// Builder for the Image widget.
pub type ImageBuilder<C = crate::geometry::Color> = WidgetBuilder<ImageCfg, C>;

/// Image configuration: the static image data to display.
pub struct ImageCfg {
    data: &'static ImageData,
}

impl ImageCfg {
    /// Creates a builder for the given image data (default size = first frame size, transparent bg).
    pub fn new<C: PixelFormat>(data: &'static ImageData) -> WidgetBuilder<ImageCfg, C> {
        WidgetBuilder { common: CommonBuilder::default(), cfg: ImageCfg { data } }
    }
}

impl<C: PixelFormat> WidgetCfg<C> for ImageCfg {
    fn default_style() -> Style {
        Style::default()
    }

    fn build(self, ui: &mut Ui<C>, parent: ObjRef, mut common: CommonBuilder<C>) -> ObjRef {
        let (fw, fh) = self.data.frames.first().map(|f| (f.w, f.h)).unwrap_or((0, 0));
        let (w, h) = common.size.unwrap_or((fw, fh));
        let r = ui.insert_node(parent, Rect::new(0, 0, w, h), alloc::boxed::Box::new(
            ImageState { data: self.data, cur: 0, last_switch: ui.time() },
        ));
        let s = common.style.take().unwrap_or_else(<Self as WidgetCfg<C>>::default_style);
        ui.set_style(r, s);
        common.apply_tail(ui, r);
        r
    }
}
